# This file was generated by GitHub Actions. DO NOT EDIT.
class Jqless < Formula
  desc "Combining jq and less for real-time JSON parsing."
  homepage "https://github.com/samsullivan/jqless"
  version "0.2.0"

  on_macos do
    url "https://github.com/samsullivan/jqless/releases/download/v0.2.0/jqless_Darwin_all.tar.gz"
    sha256 "a469606ad78eea851226f058cd68b1f1e558aa43973592142a1550eced069756"

    def install
      bin.install "jqless"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/samsullivan/jqless/releases/download/v0.2.0/jqless_Linux_arm64.tar.gz"
      sha256 "6787940e4db5626ac636e61946d70a726679be929f17aa3401bedb2f87b5d49d"

      def install
        bin.install "jqless"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/samsullivan/jqless/releases/download/v0.2.0/jqless_Linux_x86_64.tar.gz"
      sha256 "3beb02be753da3c3d61146fdf281921beb259615c91994fee61602ef1fb63dfc"

      def install
        bin.install "jqless"
      end
    end
  end
end
