# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jqless < Formula
  desc ""
  homepage "https://github.com/samsullivan/jqless"
  version "0.1.2"

  on_macos do
    url "https://github.com/samsullivan/jqless/releases/download/v0.1.2/jqless_Darwin_all.tar.gz"
    sha256 "f1a3eb7c0141a039f6cc315cd5fa079432aa478c794e642a303d246ec6fb3f08"

    def install
      bin.install "jqless"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/samsullivan/jqless/releases/download/v0.1.2/jqless_Linux_arm64.tar.gz"
      sha256 "877015b420972f33f7109b7d5db536770ba62534d362f5d6046052da29ad0673"

      def install
        bin.install "jqless"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/samsullivan/jqless/releases/download/v0.1.2/jqless_Linux_x86_64.tar.gz"
      sha256 "2cb9c310b83ac27b4ff4b1065f5130138c493e6e3910f192c9bdc6891c6d1f8f"

      def install
        bin.install "jqless"
      end
    end
  end
end
